-- MySQL Script generated by MySQL Workbench
-- seg 24 ago 2020 19:35:24 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Acomodação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Acomodação` (
  `idAcomodação` INT NOT NULL AUTO_INCREMENT,
  `capacidade` INT(4) NULL,
  `valor` DECIMAL NULL,
  `disponivel` TINYINT NOT NULL,
  PRIMARY KEY (`idAcomodação`),
  UNIQUE INDEX `idAcomodação_UNIQUE` (`idAcomodação` ASC),
  UNIQUE INDEX `capacidade_UNIQUE` (`capacidade` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dono` (
  `CPF` INT(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` INT(11) NULL,
  `email` VARCHAR(80) NOT NULL,
  `data_nascimento` DATE NULL,
  `rua` VARCHAR(50) NOT NULL,
  `numero` INT(10) NULL,
  `bairro` VARCHAR(80) NOT NULL,
  `complemento` VARCHAR(20) NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(8) NULL,
  `senha` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Animal` (
  `idAnimal` INT(11) NOT NULL,
  `nomeAnimal` VARCHAR(45) NOT NULL,
  `anoNascimento` DATE NULL,
  `observacoes` VARCHAR(150) NULL,
  `especie` VARCHAR(50) NOT NULL,
  `raca` VARCHAR(50) NOT NULL,
  `CpfDono` INT(11) NOT NULL,
  PRIMARY KEY (`idAnimal`),
  UNIQUE INDEX `idAnimal_UNIQUE` (`idAnimal` ASC),
  INDEX `fk_CpfDono_idx` (`CpfDono` ASC),
  CONSTRAINT `fk_Dono_CpfDono`
    FOREIGN KEY (`CpfDono`)
    REFERENCES `mydb`.`Dono` (`CPF`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionário` (
  `CPF` INT(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` INT(11) NULL,
  `email` VARCHAR(80) NOT NULL,
  `data_nascimento` DATE NULL,
  `rua` VARCHAR(50) NOT NULL,
  `numero` INT(10) NULL,
  `bairro` VARCHAR(80) NOT NULL,
  `complemento` VARCHAR(20) NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(8) NULL,
  `senha` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `dataEntrada` DATE NOT NULL,
  `dataSaida` DATE NULL,
  `ValorTotal` DECIMAL NULL,
  `CpfFuncionário` INT(11) NOT NULL,
  `CpfDono` INT(11) NOT NULL,
  `idAcomodação` INT NOT NULL,
  PRIMARY KEY (`idReserva`),
  UNIQUE INDEX `idReserva_UNIQUE` (`idReserva` ASC),
  INDEX `fk_CpfDono_idx` (`CpfDono` ASC),
  INDEX `fk_CpfFuncionário_idx` (`CpfFuncionário` ASC),
  UNIQUE INDEX `idAcomodação_UNIQUE` (`idAcomodação` ASC),
  CONSTRAINT `fk_CpfDono`
    FOREIGN KEY (`CpfDono`)
    REFERENCES `mydb`.`Dono` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_CpfFuncionário`
    FOREIGN KEY (`CpfFuncionário`)
    REFERENCES `mydb`.`Funcionário` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_idAcomodação`
    FOREIGN KEY (`idAcomodação`)
    REFERENCES `mydb`.`Acomodação` (`idAcomodação`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ServicoExtra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ServicoExtra` (
  `idServicoExtra` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(150) NULL,
  `valor` DECIMAL NOT NULL,
  PRIMARY KEY (`idServicoExtra`),
  UNIQUE INDEX `idServicoExtra_UNIQUE` (`idServicoExtra` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva_has_ServicoExtra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reserva_has_ServicoExtra` (
  `Reserva_idReserva` INT NOT NULL,
  `ServicoExtra_idServicoExtra` INT NOT NULL,
  `Observacoes` VARCHAR(150) NULL,
  `quantidade` INT NOT NULL,
  `dataSolicitacao` DATE NOT NULL,
  INDEX `fk_Reserva_has_ServicoExtra_ServicoExtra1_idx` (`ServicoExtra_idServicoExtra` ASC),
  INDEX `fk_Reserva_has_ServicoExtra_Reserva1_idx` (`Reserva_idReserva` ASC),
  CONSTRAINT `fk_Reserva_has_ServicoExtra_Reserva1`
    FOREIGN KEY (`Reserva_idReserva`)
    REFERENCES `mydb`.`Reserva` (`idReserva`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Reserva_has_ServicoExtra_ServicoExtra1`
    FOREIGN KEY (`ServicoExtra_idServicoExtra`)
    REFERENCES `mydb`.`ServicoExtra` (`idServicoExtra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
